<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-NJ0BPAE" failures="4" tests="6" name="Smoke Test" time="129.521" errors="0" timestamp="2023-02-28T17:31:41 EST">
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="24.659">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="24.862">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.AddEmployeeFromExcel" name="addEmployeeTest" time="25.445">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.testcases.LoginTest" name="validAdminLogin" time="2.18"/>
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserEmptyPassword" time="0.476">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.exelenter.testcases.LoginTest.validUserEmptyPassword(LoginTest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validUserEmptyPassword -->
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserInvalidPassword" time="0.0">
    <skipped/>
  </testcase> <!-- validUserInvalidPassword -->
  <testcase classname="com.exelenter.testcases.LoginTestNegative" name="userLogin" time="0.0">
    <ignored/>
  </testcase> <!-- userLogin -->
  <testcase classname="com.exelenter.testcases.AddEmployeeTest" name="addEmployeeTest" time="0.0">
    <ignored/>
  </testcase> <!-- addEmployeeTest -->
</testsuite> <!-- Smoke Test -->
