<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="8" passed="1" failed="4" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-28T17:29:30 EST" name="Smoke Test Suite" finished-at="2023-02-28T17:31:40 EST" duration-ms="129521">
    <groups>
      <group name="excel">
        <method signature="AddEmployeeFromExcel.addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@1189dd52]" name="addEmployeeTest" class="com.exelenter.testcases.AddEmployeeFromExcel"/>
      </group> <!-- excel -->
      <group name="regression">
        <method signature="AddEmployeeFromExcel.addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@1189dd52]" name="addEmployeeTest" class="com.exelenter.testcases.AddEmployeeFromExcel"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="LoginTest.validAdminLogin()[pri:0, instance:com.exelenter.testcases.LoginTest@42a48628]" name="validAdminLogin" class="com.exelenter.testcases.LoginTest"/>
        <method signature="LoginTest.validUserEmptyPassword()[pri:0, instance:com.exelenter.testcases.LoginTest@42a48628]" name="validUserEmptyPassword" class="com.exelenter.testcases.LoginTest"/>
        <method signature="LoginTest.validUserInvalidPassword()[pri:0, instance:com.exelenter.testcases.LoginTest@42a48628]" name="validUserInvalidPassword" class="com.exelenter.testcases.LoginTest"/>
        <method signature="AddEmployeeFromExcel.addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@1189dd52]" name="addEmployeeTest" class="com.exelenter.testcases.AddEmployeeFromExcel"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2023-02-28T17:29:30 EST" name="Smoke Test" finished-at="2023-02-28T17:31:40 EST" duration-ms="129521">
      <class name="com.exelenter.testcases.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.LoginTest@42a48628]" started-at="2023-02-28T17:31:20 EST" name="setUp" finished-at="2023-02-28T17:31:25 EST" duration-ms="5149" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validAdminLogin()[pri:0, instance:com.exelenter.testcases.LoginTest@42a48628]" started-at="2023-02-28T17:31:25 EST" name="validAdminLogin" finished-at="2023-02-28T17:31:27 EST" duration-ms="2180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validAdminLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.LoginTest@42a48628]" started-at="2023-02-28T17:31:27 EST" name="tearDown" finished-at="2023-02-28T17:31:31 EST" duration-ms="3701" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.LoginTest@42a48628]" started-at="2023-02-28T17:31:31 EST" name="setUp" finished-at="2023-02-28T17:31:35 EST" duration-ms="4601" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validUserEmptyPassword()[pri:0, instance:com.exelenter.testcases.LoginTest@42a48628]" started-at="2023-02-28T17:31:35 EST" name="validUserEmptyPassword" finished-at="2023-02-28T17:31:36 EST" duration-ms="476" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.exelenter.testcases.LoginTest.validUserEmptyPassword(LoginTest.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUserEmptyPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.LoginTest@42a48628]" started-at="2023-02-28T17:31:36 EST" name="tearDown" finished-at="2023-02-28T17:31:40 EST" duration-ms="3970" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="validUserInvalidPassword()[pri:0, instance:com.exelenter.testcases.LoginTest@42a48628]" started-at="2023-02-28T17:31:40 EST" name="validUserInvalidPassword" finished-at="2023-02-28T17:31:40 EST" depends-on-methods="com.exelenter.testcases.LoginTest.validUserEmptyPassword" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.exelenter.testcases.LoginTest.validUserInvalidPassword() on instance com.exelenter.testcases.LoginTest@42a48628 depends on not successfully finished methods 
[com.exelenter.testcases.LoginTest.validUserEmptyPassword() on instance com.exelenter.testcases.LoginTest@42a48628]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.exelenter.testcases.LoginTest.validUserInvalidPassword() on instance com.exelenter.testcases.LoginTest@42a48628 depends on not successfully finished methods 
[com.exelenter.testcases.LoginTest.validUserEmptyPassword() on instance com.exelenter.testcases.LoginTest@42a48628]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUserInvalidPassword -->
      </class> <!-- com.exelenter.testcases.LoginTest -->
      <class name="com.exelenter.testcases.AddEmployeeFromExcel">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@1189dd52]" started-at="2023-02-28T17:29:32 EST" name="setUp" finished-at="2023-02-28T17:29:41 EST" duration-ms="8119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@1189dd52]" started-at="2023-02-28T17:29:41 EST" name="addEmployeeTest" data-provider="readFromExcel" finished-at="2023-02-28T17:30:05 EST" duration-ms="24659" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[William]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Adams]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[willaadamss320]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[WillAdam_@2023]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Employee is not added. Username or ID already exits.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@1189dd52]" started-at="2023-02-28T17:30:05 EST" name="tearDown" finished-at="2023-02-28T17:30:10 EST" duration-ms="4433" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@1189dd52]" started-at="2023-02-28T17:30:10 EST" name="setUp" finished-at="2023-02-28T17:30:16 EST" duration-ms="5906" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@1189dd52]" started-at="2023-02-28T17:30:16 EST" name="addEmployeeTest" data-provider="readFromExcel" finished-at="2023-02-28T17:30:41 EST" duration-ms="24862" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Elizabeth]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Lee]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[elizabethleee320]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[EliLee_@2023]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Employee is not added. Username or ID already exits.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@1189dd52]" started-at="2023-02-28T17:30:41 EST" name="tearDown" finished-at="2023-02-28T17:30:45 EST" duration-ms="3886" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@1189dd52]" started-at="2023-02-28T17:30:45 EST" name="setUp" finished-at="2023-02-28T17:30:50 EST" duration-ms="5486" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addEmployeeTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@1189dd52]" started-at="2023-02-28T17:30:50 EST" name="addEmployeeTest" data-provider="readFromExcel" finished-at="2023-02-28T17:31:16 EST" duration-ms="25445" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Tyler]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Nguyen]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[tylernguyenn320]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[TylerNguyen_@2023]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Employee is not added. Username or ID already exits.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.testcases.AddEmployeeFromExcel.addEmployeeTest(AddEmployeeFromExcel.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addEmployeeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.exelenter.testcases.AddEmployeeFromExcel@1189dd52]" started-at="2023-02-28T17:31:16 EST" name="tearDown" finished-at="2023-02-28T17:31:20 EST" duration-ms="3979" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.exelenter.testcases.AddEmployeeFromExcel -->
    </test> <!-- Smoke Test -->
  </suite> <!-- Smoke Test Suite -->
</testng-results>
